[build-system]
requires = ["setuptools>=57", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "PyABSA"
version = "2.1.6"
description = "This tool provides the state-of-the-art models for aspect term extraction (ATE), aspect polarity classification (APC), and text classification (TC)."
authors = [{ name = "Yang, Heng", email = "hy345@exeter.ac.uk" }]
readme = "README.md"
repository = "https://github.com/yangheng95/PyABSA"
python = ">=3.7"

[tool.poetry.dependencies]
python = ">=3.7"
findfile = ">=2.0.0"
autocuda = ">=0.16"
metric-visualizer = ">=0.9.6"
boostaug = ">=2.3.5"
spacy = {version = "*", extras = ["lookups"]}
networkx = "*"
seqeval = "*"
update-checker = "*"
typing_extensions = "*"
tqdm = "*"
pytorch_warmup = "*"
termcolor = "*"
gitpython = "*"
transformers = ">=4.18.0"
torch = ">=1.0.0"
sentencepiece = "*"
protobuf = "<4.0.0"
pandas = "*"

[tool.poetry.extras]
docs = ["recommonmark", "nbsphinx", "sphinx-autobuild", "sphinx-rtd-theme", "sphinx-markdown-tables", "sphinx-copybutton"]
test = ["docformatter", "isort", "flake8", "pytest", "pytest-xdist"]
deploy = ["twine", "wheel", "setuptools", "gradio"]
tensorflow = ["tensorflow", "tensorflow_hub", "tensorflow_text", "tensorboardX", "tensorflow-estimator"]
optional = ["sentence_transformers", "tensorflow", "tensorflow_hub"]
dev = {features = ["docs", "test", "tensorflow", "optional", "deploy"]}